### PR TITLE
Feature/issue 10 fix

### PR DESCRIPTION
**Pull request by pentaphobe**
Fix for #10 

Only tested in MacOS Terminal as I don't have iTerm2 on this machine, but conforms to standard usage so shouldn't cause any troubles

### CODE REVIEW

**Comment by webpro** [comment]
Thanks, @pentaphobe. What does it fix? What's the difference?

**Comment by pentaphobe** [comment]
@webpro 

Current behaviour: If you have multiple terminal windows open at different paths and (say) shutdown the machine, all terminals will restore but to your home dir

PR fix: terminals will restore to their previous PWD as per default system behaviour

**Comment by pentaphobe** [comment]
NB: I've yet to work out how to get them to keep their individual histories (also the default system behaviour in MacOS) but I believe it's related

**Comment by webpro** [comment]
If I go to some dir, in two Terminal windows, and (force) quit the Terminal, that `pwd` isn't restored.

Oh, perhaps you mean after a shutdown of macOS. I have "Reopen windows/apps when logging back in" (or something like that) disabled, so this doesn't apply. Is this what you mean?

I'm on macOS High Sierra, btw.

**Comment by pentaphobe** [comment]
It should apply in either situation (assuming your preferences have old Terminal windows reopening)

If you're seeing a fresh terminal window when you restart Terminal after force quitting, then this won't help you (I've always had restore windows active, and can't check the alternative now as it was on a work machine)

..._but_ if you see the old scrollback buffer (eg. with a  prompt showing the previous PWD) then my fix should put you back where you were.

FWIW: I tested this on a fresh machine with dotfiles, however it was only running Sierra - possible there's more to do for HS?

**Comment by webpro** [comment]
The behavior I'm seeing is a change in Terminal window title:

```
Before: ~/.dotfiles — -bash — 89x24
After:  .dotfiles — ~/.dotfiles — -bash — 89x24
```

Looks like `update_terminal_cwd` is indeed doing this:

```
❯ type update_terminal_cwd 
update_terminal_cwd is a function
update_terminal_cwd () 
{ 
    local url_path='';
    { 
        local i ch hexch LC_CTYPE=C LC_ALL=;
        for ((i = 0; i < ${#PWD}; ++i))
        do
            ch="${PWD:i:1}";
            if [[ "$ch" =~ [/._~A-Za-z0-9-] ]]; then
                url_path+="$ch";
            else
                printf -v hexch "%02X" "'$ch";
                url_path+="%${hexch: -2:2}";
            fi;
        done
    };
    printf '\e]7;%s\a' "file://$HOSTNAME$url_path"
}
```

Updating the Terminal title is also in the prompt command this dotfiles repo: https://github.com/webpro/dotfiles/blob/master/system/.prompt#L80-L83

So far, this only looks like a regression to me :-)

**Comment by pentaphobe** [comment]
> So far, this only looks like a regression to me :-)

Oh dear! :)

Well, if you can hold until next week when I'm back on the work machine in question then I'll give it another pass - should be easy enough to reconcile both (he said, naïvely)

Feel free to close the PR if you'd prefer - otherwise I'll double back when I've more to show


Thanks!

**Comment by webpro** [comment]
No problem, I'll keep this open and I'm happy to test on High Sierra. Maybe others will chime in as well.

**Comment by webpro** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
